[package]
name = "xdb"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
cpp_demangle = "0.5.1"
iced-x86 = "1.21.0"
libc = "0.2"
memmap2 = "0.9.10"
nix = { version = "0.31", features = ["fs", "personality", "process", "ptrace", "signal", "uio"] }
rustyline = "17"

[build-dependencies]
cc = "1"
